-- ==============================================================================
-- CIRUGÍA DE ARQUITECTURA V6: TABLAS RESTANTES Y PRIMARY KEYS
-- ==============================================================================

-- 1. CREACIÓN DE LA TABLA CATEGORIAS
-- Esta tabla resuelve el error 404 (Failed to load resource: the server responded with a status of 404)
CREATE TABLE IF NOT EXISTS public.categorias (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL
);

-- Aseguramos que la tabla pueda ser vista públicamente
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Activar visualización pública de categorias"
    ON public.categorias FOR SELECT
    USING (true);

-- Poblamos la tabla con las categorías existentes para que el Select inicial no venga vacío
INSERT INTO public.categorias (nombre) VALUES
    ('Basurero'),
    ('Canalización'),
    ('Cielo falso'),
    ('Cintas'),
    ('Electricidad'),
    ('Extractores de aire'),
    ('Grifería'),
    ('Herramientas'),
    ('Iluminación LED'),
    ('Maquinaria'),
    ('Selladora')
ON CONFLICT DO NOTHING;

-- 2. FIJAR PRIMARY KEY EN PRODUCTOS PARA HABILITAR EL .select() DE POSTGREST
-- El error "La base de datos aceptó el comando, pero no devolvió el registro"
-- ocurre cuando PostgREST no puede localizar el ID/Key lógico devuelto por la transacción.
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_type = 'PRIMARY KEY' AND table_name = 'productos') THEN
        ALTER TABLE public.productos ADD PRIMARY KEY (sku);
    END IF;
END $$;

-- 3. RECARGAR LA MEMORIA DE SCHEMA POSTGREST (OBLIGATORIO)
NOTIFY pgrst, 'reload schema';
